project:
  name: predicat

models:
  - na2008
  - coicop
  
model_conf:
  na2008:
    file: model_na2008.bin
    date: 2020/12/14

  iri:
    file:
    date:  
  
  coicop:
    file: model_coicop10.bin
    date: 2021/11/02
